db_config:
  adapter: sqlite3
  database: twitter.sqlite3

log_file: convo_finder.log

seed:
  - ladygaga
  - justinbieber
  - katyperry
  - rihanna
  - britneyspears
  - BarackObama
  - shakira
  - taylorswift13
  - KimKardashian
  - YouTube
  - NICKIMINAJ
  - Oprah
  - jtimberlake
  - TheEllenShow
  - selenagomez
  - twitter
  - KAKA
  - Cristiano
  - Eminem
  - aplusk
  - BrunoMars
  - chrisbrown
  - SnoopDogg
  - Pink
  - twitter_es
  - JLo
  - aliciakeys
  - JimCarrey
  - Drake
  - ddlovato
  - cnnbrk
  - OfficialAdele
  - kanyewest
  - ParisHilton
  - TwitPic
  - charliesheen
  - coldplay
  - LilTunechi
  - ashleytisdale
  - MariahCarey
  - BillGates
  - UberSoc
  - KhloeKardashian
  - RyanSeacrest
  - instagram
  - 50cent
  - programapanico
  - ivetesangalo
  - RealWizKhalifa
  - MileyCyrus
  - KourtneyKardash
  - tyrabanks
  - AlejandroSanz
  - ricky_martin
  - iamdiddy
  - danieltosh
  - ConanOBrien
  - FCBarcelona
  - jimmyfallon
  - SHAQ
  - Pitbull
  - AvrilLavigne
  - NBA
  - juanes
  - ClaudiaLeitte
  - LucianoHuck
  - nytimes
  - Ludacris
  - davidguetta
  - KingJames
  - JessicaSimpson
  - Harry_Styles
  - justdemi
  - snooki
  - PerezHilton
  - onedirection
  - CNN
  - realmadrid
  - agnezmo
  - google
  - rustyrockets
  - chelseahandler
  - paulocoelho
  - NiallOfficial
  - JessieJ
  - marcosmion
  - Njr92
  - Beyonce
  - SabrinaSatoReal
  - rafinhabastos
  - DalaiLama
  - TreySongz
  - Anahi
  - eonline
  - twitcam
  - Real_Liam_Payne
  - MTV
  - OMGFacts
  - Louis_Tomlinson
  - WayneRooney
  - KevinHart4real
  - espn
  - stephenfry
  - nickjonas
  - paurubio
  - tomhanks
  - UsherRaymondIV
  - noaheverett
  - Calle13Oficial
  - zaynmalik
  - BreakingNews
  - sherinamunaf
  - 106andpark
  - funnyordie
  - 10Ronaldinho
  - facebook
  - marcoluque
  - thalia
  - jason_mraz
  - luansantana
  - victoriabeckham
  - andresiniesta8
  - lindsaylohan
  - TheOnion
  - iamwill
  - peoplemag
  - EvaLongoria
  - DJPaulyD
  - joejonas
  - KELLYROWLAND
  - ActuallyNPH
  - snaptu
  - sule_prikitw
  - JonasBrothers
  - davidbisbal
  - RevRunWisdom
  - cesc4official
  - ChespiritoRGB
  - TIME
  - johnlegend
  - StephenAtHome
  - souljaboy
  - showdavida
  - lilyrosecooper
  - BBCBreaking
  - nfl
  - Legendarios
  - ochocinco
  - lancearmstrong
  - NickCannon
  - 3gerardpique
  - DwyaneWade
  - SportsCenter
  - realwbonner
  - rede_globo
  - rodrigovesgo
  - jessicaalba
  - Tyga
  - DaniloGentili
  - Fearnecotton
  - LennyKravitz
  - LMFAO
  - nicolerichie
  - KendallJenner
  - ClaroRonaldo
  - oceara
  - vidialdiano
  - daddy_yankee
  - EmWatson
  - Carles5puyol
  - IAMQUEENLATIFAH
  - luisfonsi
  - Notebook
  - RobKardashian
  - DwightHoward
  - MarceloTas
  - DjKingAssassin
  - SeanKingston
  - SandyLeah
  - OneLouderApps
  - chavezcandanga
  - annecurtissmith
  - RealLamarOdom
  - keshasuxx
  - detikcom
  - afgansyah_reza
  - FloydMayweather
  - TomCruise
  - SarahKSilverman
  - DulceMaria
  - tonyhawk
  - rainnwilson
  - shitmydadsays
  - hootsuite
  - radityadika
  - rioferdy5
  - SrBachchan
  - eRock
  - VINNYGUADAGNINO
  - whitehouse
